server:
  port: 8080

spring:
  application:
    name: Portpholio-site

  datasource:
    url: jdbc:mysql://localhost:3306/portfolio-site
    username: root
    password: Samara2020-
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        database-platform: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

portfolio:
  admin:
    username: admin
    password: admin123


